apiVersion: v1
kind: ConfigMap
metadata:
  name: mrm-weather
data:
  appsettings.k8s.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ApplicationInsights": {
        "ConnectionString": "InstrumentationKey=14c72dc5-3eee-4afe-8509-3edf3b216967;IngestionEndpoint=https://westus3-1.in.applicationinsights.azure.com/"
      },
      "ExternalApiUri": "https://www.bing.com"
    }